steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/gads-proxy:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gads-proxy:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gads-proxy'
      - '--image=gcr.io/$PROJECT_ID/gads-proxy:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
images:
  - 'gcr.io/$PROJECT_ID/gads-proxy:$COMMIT_SHA'
